parameters:
  name: ''
  pool: ''
  nugetVersion: 5.8.0
  appInsightsInstrumentationKey: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  variables:
    instrumentationKey: ${{ parameters.appInsightsInstrumentationKey }}
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet'
    inputs:
      versionSpec: ${{ parameters.nugetVersion }}

  - task: PowerShell@2
    displayName: 'restore & build Release'
    inputs: 
      filePath: build.ps1
      workingDirectory: ./
      arguments: Release -appInsightsInstrumentationKey $(instrumentationKey)
      pwsh: true

  - task: VSTest@2
    displayName: 'Unit Tests'
    inputs:
      testAssemblyVer2: |
       **\Release\**\*.UnitTests.dll
       !**\*TestAdapter.dll
       !**\obj\**
    diagnosticsEnabled: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: VS2019 Extension'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/VsIntegration/bin/Release/TechTalk.SpecFlow.VisualStudioIntegration.vsix'
      ArtifactName: VS2019

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: VS2017 Extension'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/VsIntegration2017/bin/Release/TechTalk.SpecFlow.VsIntegration.2017.vsix'
      ArtifactName: VS2017

  - task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@19
    displayName: 'WhiteSource Bolt'
    inputs:
      advance: true
